import {msgTag} from '../../../common/lang';
const msg = msgTag('solardevice');

export default [{
    name: msg('BXT.State'),
    alias: 'BXTF.State',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    isStatus: true
}, {
    name: msg('BXT.freq'),
    alias: 'BXTF.Freq',  
    unit: 'Hz',
    tableNo: 62,
    fieldNo: 9,
    icon: true,
    iconName: msg('BXT.freq')
}, {
    name: msg('BXT.freq2'),
    alias: 'BXTF.Freq2',  
    unit: 'Hz',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.temp'),
    alias: 'BXTF.Temp',  
    unit: '℃',
    tableNo: 62,
    fieldNo: 9,
    icon: true,
    iconName: msg('BXT.temp')
}, {
    name: msg('BXT.IaBr1'),
    alias: 'BXTF.IaBr1',  
    unit: 'A',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.IbBr1'),
    alias: 'BXTF.IbBr1',  
    unit: 'A',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.IcBr1'),
    alias: 'BXTF.IcBr1',  
    unit: 'A',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.UaBr1'),
    alias: 'BXTF.UaBr1',  
    unit: 'V',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.UbBr1'),
    alias: 'BXTF.UbBr1',  
    unit: 'V',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.UcBr1'),
    alias: 'BXTF.UcBr1',  
    unit: 'V',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.ActPowPhBr1'),
    alias: 'BXTF.ActPowPhBr1',  
    unit: 'kW',
    tableNo: 62,
    fieldNo: 9
}, {
    name: msg('BXT.ReActPowPhBr1'),
    alias: 'BXTF.ReActPowPhBr1',  
    unit: 'kVar',
    tableNo: 62,
    fieldNo: 9
}, {
    name: msg('BXT.CosPhiBr1'),
    alias: 'BXTF.CosPhiBr1',  
    unit: '',
    tableNo: 62,
    fieldNo: 9
}, {
    name: msg('BXT.IaBr21'),
    alias: 'BXTF.IaBr2',  
    unit: 'A',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.IbBr21'),
    alias: 'BXTF.IbBr2',  
    unit: 'A',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.IcBr21'),
    alias: 'BXTF.IcBr2',  
    unit: 'A',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.UaBr21'),
    alias: 'BXTF.UaBr2',  
    unit: 'V',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.UbBr21'),
    alias: 'BXTF.UbBr2',  
    unit: 'V',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.UcBr21'),
    alias: 'BXTF.UcBr2',  
    unit: 'V',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.ActPowPhBr21'),
    alias: 'BXTF.ActPowPhBr2',  
    unit: 'kW',
    tableNo: 62,
    fieldNo: 9
}, {
    name: msg('BXT.ReActPowPhBr21'),
    alias: 'BXTF.ReActPowPhBr2',  
    unit: 'kVar',
    tableNo: 62,
    fieldNo: 9
}, {
    name: msg('BXT.CosPhiBr21'),
    alias: 'BXTF.CosPhiBr2',  
    unit: '',
    tableNo: 62,
    fieldNo: 9
}, {
    name: msg('BXT.IaBr22'),
    alias: 'BXTF.IaBr22',  
    unit: 'A',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.IbBr22'),
    alias: 'BXTF.IbBr22',  
    unit: 'A',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.IcBr22'),
    alias: 'BXTF.IcBr22',  
    unit: 'A',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.UaBr22'),
    alias: 'BXTF.UaBr22',  
    unit: 'V',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.UbBr22'),
    alias: 'BXTF.UbBr22',  
    unit: 'V',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.UcBr22'),
    alias: 'BXTF.UcBr22',  
    unit: 'V',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.ActPowPhBr22'),
    alias: 'BXTF.ActPowPhBr22',  
    unit: 'kW',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.ReActPowPhBr22'),
    alias: 'BXTF.ReActPowPhBr22',  
    unit: 'kVar',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.CosPhiBr22'),
    alias: 'BXTF.CosPhiBr22',  
    unit: '',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.freq22'),
    alias: 'BXTF.Freq22',  
    unit: 'Hz',
    tableNo: 62,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.LoadSwitchClose'),
    alias: 'BXTF.LoadSwitchClose',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.LoadSwitchFault'),
    alias: 'BXTF.LoadSwitchFault',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.OilTempHigh'),
    alias: 'BXTF.OilTempHigh',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.OilLow'),
    alias: 'BXTF.OilLow',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.OilPressure'),
    alias: 'BXTF.OilPressure',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.LightGas'),
    alias: 'BXTF.LightGas',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.HeavyGas'),
    alias: 'BXTF.HeavyGas',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.SmogAlarm'),
    alias: 'BXTF.SmogAlarm',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.SGZ'),
    alias: 'BXTF.SGZ',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.HighVolDoor'),
    alias: 'BXTF.HighVolDoor',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.LowVolDoor'),
    alias: 'BXTF.LowVolDoor',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.SingleBreaker01'),
    alias: 'BXTF.SingleBreaker01',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    hidden: true
}, {
    name: msg('BXT.SingleBreaker02'),
    alias: 'BXTF.SingleBreaker02',  
    unit: '',
    tableNo: 61,
    fieldNo: 9,
    hidden: true
}]